### ISSUE TITLE
Hitachi RE11T1 Unable to pair

### ISSUE THREAD

**Issue by shengweitw** [LouisLee985/Homekit-Air-Conditioner#10]
![image](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/assets/106579822/dca55943-f708-4da3-9c7d-f9bc1ddfc533)
![image](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/assets/106579822/cca5cd1c-ff6f-431a-8a05-f32e3c716432)

I saw your definition, it should be the same as the picture above.

Can Hitachi's remote control be recognized?

The remote control model is RE11T1.

**Comment by LouisLee985** [comment]
https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/issues/2#issuecomment-1403375298

RF11T1 remote (HITACHI_AC344)

Long press Button IO0 5-10 second: Set up the infrared protocol

https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/issues/2#issuecomment-1403490696

**Comment by LouisLee985** [comment]
Now flash v1.3.0, set up protocol in wifisetup,
HITACHI_AC344 is 85.
![ir_protocol](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/assets/88962972/8a25271d-ba0f-4caf-a341-0f7d74a39b32)
