### ISSUE TITLE
Modify pins for ESP-01M remote

### ISSUE THREAD

**Issue by ferbulous** [LouisLee985/Homekit-Air-Conditioner#11]
Hello, I have this ir remote

![image](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/assets/24526737/4447d246-4b93-4651-8038-9464a5c11a45)

How do I change the pin to these?
transmitter - gpio04
receiver - gpio14

**Comment by LouisLee985** [comment]
ESP-01M_IR_TR built-in 1MB flash,

For this repository, FLASH must be 2MB at least.

Download gerber,make PCB,soldering.

https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/blob/main/hardware/README.md
