### ISSUE TITLE
能否不要用遙控器配對?

### ISSUE THREAD

**Issue by shengweitw** [LouisLee985/Homekit-Air-Conditioner#12]
不知道為何，Hitachi AC433 使用遙控器，它就是不會配對，這情況下，有別的配對方式嗎?  例如網頁配置或者其它的方式?

**Comment by LouisLee985** [comment]
Check your hardware like infrared emitter is good and properly soldering.
You can test it by [IRrecvDumpV2.bin](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/tree/8b12f5ae37ed0b88d269cb3e1c8cddda015dad4b/IR-Raw-Receiver).

**Comment by LouisLee985** [comment]
https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/issues/10#issuecomment-2059252716
