### ISSUE TITLE
Gpio help me

### ISSUE THREAD

**Issue by kivanc87** [LouisLee985/Homekit-Air-Conditioner#18]
Hello, what are the gpios in the circuit you made? Also, I have a universal product. How can I adapt its GPIOs to your software?

![image](https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/assets/83796711/b82c38dc-d33b-45a2-a3f8-9e390214bcc8)

![image](https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/assets/83796711/59454e3a-317d-4dd3-b63b-bb63797c4248)

**Comment by LouisLee985** [comment]
https://templates.blakadder.com/auvisio_S06.html

BK7231N
or
TYWE3S
?

**Comment by kivanc87** [comment]
I made the pins and introduced the remote control, but I think the IR codes did not give any commands. Can you help me if I give you the IR raw commands?

**Comment by LouisLee985** [comment]
You can test by
[IRsendDemo.ino](https://github.com/crankyoldgit/IRremoteESP8266/blob/master/examples/IRsendDemo/IRsendDemo.ino)
for ESP.

**Comment by kivanc87** [comment]
Can we change the irsend irrecv pin in your software?
