### ISSUE TITLE
日立空調能用嗎? RAS-28NK

### ISSUE THREAD

**Issue by shengweitw** [LouisLee985/Homekit-Air-Conditioner#2]
請問這類空調是否可用?   遙控器型號: RS11T3

**Comment by LouisLee985** [comment]
https://github.com/crankyoldgit/IRremoteESP8266/blob/master/SupportedProtocols.md

**Comment by shengweitw** [comment]
請問一下，你的MCU接腳定義與https://github.com/Mixiaoxiao/ESP8266-IR-HOMEKIT相同嗎?

**Comment by shengweitw** [comment]
https://github.com/Mixiaoxiao/ESP8266-IR-HOMEKIT

**Comment by LouisLee985** [comment]
Yes,but no IO13.

**Comment by shengweitw** [comment]
我的遙控器配對，無效，但在上一個版本我可以用RF11T1 remote (HITACHI_AC344)這個設定來控制。這邊該如何設定它使用RF11T1 remote (HITACHI_AC344)這個設定?

**Comment by LouisLee985** [comment]
遙控器配對：    长按 IO0 按键5秒， LED 2次/秒  闪烁， 松开按键，在15秒内用普通空调遥控器对准此项目上的遥控接收头(IR_R)按一下开关机键，等待 LED 闪烁停止。
[IO0 按键定义 ](https://github.com/LouisLee985/Homekit_ESP_AC_IRemote#button-io0-%E6%8C%89%E9%94%AE%E5%AE%9A%E4%B9%89)

In [IRremoteESP8266.h](https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/IRremoteESP8266.h) line 1098：
HITACHI_AC344,  // 85

此项目bin文件  与  [ESP8266-IR-HOMEKIT](https://github.com/Mixiaoxiao/ESP8266-IR-HOMEKIT) 不是同一软件，没有版本延续的关系。
