### ISSUE TITLE
RE11T1 日立遙控器無法配對

### ISSUE THREAD

**Issue by shengweitw** [LouisLee985/Homekit-Air-Conditioner#20]
使用IRrecvDumpV2.bin調適，在介面是可以看到訊號的，如下:
Timestamp : 000050.215,  Library : v2.8.2
Code : 0x7496D4FB (214 Bits)
                            Protocol: -1 (UNKNOWN), uint16_t rawData[427] = {3466, 1598,  512, 1178,  510, 438,  484, 436,  486, 436,  486, 436,  488, 436,  486, 436,  486, 436,  486, 436,  488, 436,  488, 436,  488, 436,  488, 1178,  512, 434,  486, 436,  488, 436,  486, 436,  486, 436,  488, 436,  486, 436,  486, 436,  486, 438,  484, 438,  486, 438,  484, 438,  484, 438,  484, 438,  486, 438,  482, 440,  482, 440,  480, 1186,  510, 436,  482, 1182,  510, 1178,  512, 1178,  508, 1180,  510, 1178,  508, 1180,  508, 440,  452, 1212,  506, 1182,  508, 1182,  508, 1180,  508, 1180,  506, 1182,  508, 1180,  508, 1182,  508, 1182,  508, 438,  482, 442,  480, 444,  480, 442,  480, 442,  480, 442,  482, 442,  480, 442,  482, 442,  482, 440,  484, 1180,  510, 1178,  512, 436,  486, 438,  484, 1180,  510, 1178,  510, 1178,  510, 1180,  508, 438,  484, 440,  484, 1180,  508, 1180,  508, 440,  484, 440,  484, 440,  482, 1182,  508, 440,  484, 440,  482, 1182,  506, 440,  484, 440,  482, 1184,  504, 1184,  504, 442,  480, 1186,  502, 1186,  502, 446,  478, 1186,  500, 1188,  498, 446,  476, 1192,  472, 1218,  470, 474,  474, 448,  454, 1214,  472, 472,  448, 474,  448, 476,  446, 476,  444, 478,  446, 1222,  468, 1220,  466, 476,  446, 1222,  464, 1226,  462, 1226,  462, 480,  442, 482,  442, 1226,  462, 480,  444, 480,  440, 1232,  434, 1272,  416, 506,  418, 1272,  438, 1248,  440, 484,  416, 1274,  414, 1274,  414, 510,  414, 510,  414, 1276,  412, 512,  412, 512,  412, 512,  410, 514,  408, 514,  408, 514,  406, 520,  402, 520,  404, 1284,  404, 1286,  404, 1284,  404, 1286,  402, 1286,  402, 1286,  404, 1286,  402, 1286,  402, 544,  380, 544,  378, 544,  380, 544,  380, 544,  378, 544,  378, 544,  378, 544,  378, 1286,  402, 1286,  402, 1288,  402, 1308,  380, 1310,  378, 1310,  378, 1310,  380, 1308,  380, 544,  378, 546,  378, 544,  380, 544,  378, 546,  378, 544,  378, 544,  378, 544,  378, 1310,  378, 1310,  378, 1310,  378, 1312,  378, 1310,  378, 1310,  378, 1310,  378, 1310,  378, 546,  378, 546,  376, 546,  376, 546,  378, 546,  376, 546,  376, 546,  354, 594,  330, 1334,  354, 1336,  352, 1336,  352, 1360,  328, 1336,  352, 1360,  328, 1360,  328, 1360,  328, 594,  328, 594,  328, 594,  328, 596,  328, 594,  328, 596,  326, 596,  326, 620,  302, 1362,  326, 1362,  326, 1376,  314, 1386,  302, 1388,  302, 1388,  300, 1388,  300, 1388,  300, 1414,  274, 1412,  276, 650,  274, 650,  274, 1416,  254, 694,  222, 1468,  220, 706,  218, 728,  194, 730,  194, 1520,  168, 1572,  88};  // UNKNOWN 7496D4FB

Timestamp : 000051.456,  Library : v2.8.2
Code : 0xAF6BBDC (85 Bits)
                          Protocol: -1 (UNKNOWN), uint16_t rawData[169] = {222, 1442,  248, 1440,  248, 1414,  298, 1388,  300, 1388,  300, 1388,  300, 622,  300, 622,  300, 622,  300, 622,  300, 622,  302, 622,  302, 622,  302, 1362,  326, 1362,  326, 1362,  328, 1362,  326, 1362,  326, 1362,  328, 1360,  328, 1362,  328, 596,  328, 1360,  328, 1362,  328, 596,  326, 596,  328, 596,  328, 596,  326, 596,  326, 596,  326, 596,  326, 596,  326, 1360,  328, 1362,  328, 1360,  328, 1360,  328, 1360,  326, 1362,  328, 596,  326, 596,  328, 594,  328, 596,  326, 596,  328, 596,  328, 596,  326, 596,  326, 1362,  328, 1362,  328, 1360,  328, 1362,  328, 1360,  328, 1360,  328, 1362,  328, 1360,  328, 596,  326, 598,  326, 596,  326, 596,  328, 596,  326, 598,  326, 622,  302, 622,  300, 1364,  326, 1388,  302, 1388,  300, 1388,  300, 1388,  300, 1388,  300, 1388,  300, 1390,  298, 650,  274, 648,  274, 650,  272, 650,  272, 652,  248, 700,  222, 702,  222, 702,  222, 1468,  220, 1494,  194, 1520,  168, 1520,  168, 1548,  134, 1580,  86};  // UNKNOWN AF6BBDC
但，進入遙控器配對時，就是無法正常配對。請問這是為何?

**Comment by shengweitw** [comment]
或者可以直接設定成HITACHI_AC344，這個模式就好，我的冷氣全是走這個模式的

**Comment by LouisLee985** [comment]
It must be `Protocol: 85 (HITACHI_AC344)`, not `Protocol: -1 (UNKNOWN)`,check your hardware.
If only set to HITACHI_AC344 in BIN , may be no feedback feature.<br>https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/releases/download/v1.2.0/Air_Conditioner_Remote_1.2.0.085.bin

**Comment by shengweitw** [comment]
![IR](https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/assets/106579822/e5d1bd88-ce5d-4d49-96f4-3b882518e478)

IR_T(OUT) | IO14
IR_R(IN) | IO12

這樣接，對嗎?
或者您開發的板子，有購買連結嗎?

> It must be `Protocol: 85 (HITACHI_AC344)`, not `Protocol: -1 (UNKNOWN)`,check your hardware. If only set to HITACHI_AC344 in BIN , may be no feedback feature.https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/releases/download/v1.2.0/Air_Conditioner_Remote_1.2.0.085.bin

您給我的這個可以用，但它沒有風速可以調整。

**Comment by shengweitw** [comment]
我用您提供的Air_Conditioner_Remote_1.2.0.085.bin，發出訊號，得到的卻是
Timestamp : 000258.674,  Library : v2.8.2
Code : 0x4EEDB95C (139 Bits)
                            Protocol: -1 (UNKNOWN), uint16_t rawData[277] = {3344, 1698,  426, 1238,  424, 456,  448, 460,  446, 458,  446, 460,  446, 462,  444, 456,  448, 470,  444, 482,  420, 458,  446, 482,  422, 460,  444, 1230,  426, 484,  420, 484,  422, 484,  422, 482,  420, 482,  422, 484,  422, 482,  422, 484,  422, 482,  422, 482,  422, 484,  420, 484,  420, 484,  420, 484,  422, 482,  420, 486,  424, 480,  424, 1228,  424, 482,  422, 1232,  394, 1260,  394, 1238,  416, 1236,  422, 1232,  424, 1230,  450, 482,  424, 1204,  452, 1202,  454, 1200,  454, 1198,  456, 1200,  452, 1202,  452, 1202,  450, 1204,  450, 1204,  448, 456,  446, 458,  446, 458,  446, 458,  442, 462,  440, 462,  442, 464,  442, 464,  440, 466,  438, 486,  414, 1240,  390, 1264,  414, 490,  414, 490,  390, 1264,  390, 1266,  390, 1266,  388, 1266,  386, 518,  386, 518,  386, 1268,  384, 1270,  384, 520,  382, 522,  382, 522,  380, 1276,  376, 528,  374, 530,  376, 1278,  374, 530,  374, 530,  374, 1280,  374, 1280,  374, 530,  374, 1280,  374, 1280,  374, 530,  376, 1278,  374, 1282,  374, 532,  372, 1282,  372, 1282,  372, 532,  372, 554,  348, 1306,  350, 556,  350, 554,  348, 556,  348, 556,  348, 554,  350, 1306,  348, 1306,  348, 556,  348, 1306,  350, 1304,  348, 1306,  350, 556,  348, 556,  326, 578,  324, 1330,  324, 580,  322, 1332,  324, 1332,  324, 580,  324, 1330,  324, 1332,  324, 1352,  302, 606,  298, 1356,  298, 606,  298, 608,  298, 1356,  298, 608,  296, 608,  296, 608,  296, 608,  296, 610,  296, 628,  276, 610,  296, 636,  268, 1386,  254, 1400,  244, 1412,  242, 1412,  242, 1438,  216, 1438,  216, 1464,  188, 1468,  188, 770,  122};  // UNKNOWN 4EEDB95C

VS1838b的接法，是根據您提供的GPIO12，實在想不出來是哪邊做錯了

**Comment by LouisLee985** [comment]
Read datasheet of your VS1838b , then connect to Nodemcu.
look like:
![test](https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/assets/88962972/13f0cba3-a67f-45dd-af36-1a73f4e26248)
or 
https://github.com/adafruit/Adafruit-Infrared-IR-Remote-Transceiver
https://github.com/sparkfun/IR_Receiver_Breakout

**Comment by shengweitw** [comment]
瞭解，我明天試著完成上面的電路圖。另外，我的模組是可以收到AC1的訊號，如下
Timestamp : 001365.802,  Library : v2.8.2
Code : 0xB2AE4D51F061C40000000010D8 (104 Bits)
                                              Protocol: 41 (HITACHI_AC1), Model: 2 (R-LT0541-HTA-B), Power: Off, Power Toggle: On, Mode: 6 (Cool), Temp: 24C, Fan: 1 (Auto), Swing(V) Toggle: Off, Swing(V): Off, Swing(H): Off, Sleep: Off, On Timer: Off, Off Timer: Off
uint16_t rawData[211] = {3372, 3358,  436, 1234,  414, 356,  454, 1234,  416, 1234,  414, 344,  466, 372,  436, 1236,  416, 372,  436, 1236,  414, 374,  436, 1236,  412, 376,  434, 1234,  416, 1236,  414, 1236,  412, 376,  436, 374,  434, 1236,  414, 374,  434, 376,  434, 1234,  416, 1236,  414, 374,  436, 1234,  414, 376,  434, 1236,  414, 374,  434, 1234,  418, 372,  434, 374,  434, 374,  436, 1234,  416, 1234,  416, 1234,  414, 1234,  414, 1236,  414, 376,  434, 374,  434, 374,  434, 374,  434, 376,  434, 1234,  414, 1236,  414, 374,  434, 374,  434, 376,  434, 396,  412, 1236,  414, 1234,  416, 1234,  416, 376,  434, 374,  436, 376,  432, 1236,  414, 396,  412, 378,  432, 376,  434, 378,  430, 398,  412, 396,  412, 376,  434, 396,  412, 398,  412, 396,  412, 396,  412, 396,  412, 398,  412, 396,  414, 396,  412, 396,  412, 398,  412, 398,  410, 398,  414, 396,  412, 398,  386, 424,  386, 424,  410, 398,  414, 396,  410, 400,  408, 402,  406, 404,  380, 430,  380, 430,  380, 430,  382, 428,  384, 424,  410, 398,  412, 396,  414, 394,  416, 392,  416, 1208,  442, 392,  416, 392,  416, 394,  416, 372,  436, 1210,  438, 1212,  436, 374,  432, 1216,  434, 1216,  430, 378,  428, 380,  428, 382,  428};  // HITACHI_AC1
                                  uint8_t state[13] = {0xB2, 0xAE, 0x4D, 0x51, 0xF0, 0x61, 0xC4, 0x00, 0x00, 0x00, 0x00, 0x10, 0xD8};
