### ISSUE TITLE
LG ac ir remote

### ISSUE THREAD

**Issue by kivanc87** [LouisLee985/Homekit-Air-Conditioner#21]
Hello, I have an LG air conditioner and I could not adapt it to it. I put it into recognition mode and when I press the air conditioner's remote control, it blinks but it does not receive any commands. I would be very grateful if you could help me.

**Comment by LouisLee985** [comment]
- Long pressed  5-10 second: Set up the infrared protocol
- Long pressed 10-15 second: Restore settings

**Comment by kivanc87** [comment]
I did it but it didn't work. I tried it on a different air conditioner and it works, but I couldn't get it to work on LG. I would be very happy if you help

**Comment by kivanc87** [comment]
kivancsenol@hotmail.com

this is my email

**Comment by kivanc87** [comment]
I want to customize the air conditioner for myself. How can I make changes to the LG air conditioner codes?

**Comment by kivanc87** [comment]
![image](https://github.com/user-attachments/assets/8c8bf98b-a6f1-48ce-8d0b-453542fb9568)

I could never recognize the remote control. I put a screenshot.
