### ISSUE TITLE
我需要你的幫助

### ISSUE THREAD

**Issue by aam712305** [LouisLee985/Homekit-Air-Conditioner#3]
能跟你購買特製化功能的固件嗎?
a9228836a@gmail.com

**Comment by LouisLee985** [comment]
愿闻其详

**Comment by aam712305** [comment]
能用email聯絡嗎?

**Comment by aam712305** [comment]
哈囉!

**Comment by aam712305** [comment]
> 願聞其詳

除了冷氣外還能控制其他的設備嗎？
能用控制電子郵件聯繫嗎？

**Comment by LouisLee985** [comment]
不能控制其他设备。

[HomeKit Accessory Protocol Specification(Noncommercial Version) Release R2](https://developers.apple.com/homekit/faq)
Noncommercial Version

**Comment by aam712305** [comment]
好的 了解 謝謝~
