### ISSUE TITLE
请问IRM和GPIO0引脚定义在哪

### ISSUE THREAD

**Issue by addcjy1** [LouisLee985/Homekit-Air-Conditioner#5]
想要更改IRM引脚，用以尝试配对涂鸦成品遥控板，以及GPIO0的功能尝试转移至其他IO，可否告知这两个引脚定义位置，我貌似没看到

**Comment by addcjy1** [comment]
@LouisLee985

**Comment by LouisLee985** [comment]
[AC_IRemote_ESP-01F PIN](https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/tree/main/hardware#ac_iremote_esp-01f-pin)

**Comment by LouisLee985** [comment]
按键：IO0(D3)，即NodeMCU开发板上的Flash按键

**Comment by addcjy1** [comment]
很抱歉，我在src中的各个文件没有看到这几个引脚的定义，只看到了IRCoolixAC ac(14)以及LED_PIN 2，能否再请教一下我修改这几个引脚定义的话应该在何处修改，感谢您耐心解答

**Comment by LouisLee985** [comment]
需要改成什么pin？
涂鸦的mcu 和8266兼容？

**Comment by addcjy1** [comment]
涂鸦的TYWE3S模块集成的是ESP8266，官方介绍里IO14为IR LED，IO5为IRM，KEY为IO13，这是涂鸦官方的介绍 https://developer.tuya.com/cn/docs/iot/tysw012-round-universal-remote-control?id=K9lnm617oupeb

**Comment by addcjy1** [comment]
我在涂鸦的设备刷入了Mixiaoxiao大佬的[ESP8266-IR-HOMEKIT](https://github.com/Mixiaoxiao/ESP8266-IR-HOMEKIT)，并在WEB端修改了IO引脚，使用是正常的，但是因为Mixiaoxiao固件的码库不支持，且该项目咨询了Mixiaoxiao已经停止维护，在issues中看到了您对他人的回答，所以想尝试一下

**Comment by LouisLee985** [comment]
此固件不支持TYWE3S模块。FLASH is only 1MB.

**Comment by addcjy1** [comment]
能否再麻烦您按以下IO生成一份固件，涂鸦的图片不清晰，KEY看着像IO13又像IO15，[Air_Conditioner_Remote_1.6.0-TYSW-012.bin](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/blob/main/firware_bin/Air_Conditioner_Remote_1.6.0-TYSW-012.bin)这个版本KEY未生效，尚无法测试红外功能
IO14为IR LED，IO5为IRM，IO15为KEY，IO4为LED

**Comment by LouisLee985** [comment]
按下key 5秒后，led闪吗？

**Comment by addcjy1** [comment]
不闪，LED只在上电瞬间闪烁，涂鸦官方说明KEY是IO13，看原理图比较模糊看着又像IO15，目前没有万用表可以测试

**Comment by LouisLee985** [comment]
重刷试试。
短接IO0和GND 5秒，当KEY使用。

**Comment by addcjy1** [comment]
感谢指教，涂鸦焊点脱落，只能等上班有工具了修复再测试，手头Nodemcu只有32S没有8266可测试

**Comment by jcober** [comment]
Air_Conditioner_Remote_1.6.0-TYSW-012.bin 刷入后[IO0 按键定义]功能正常 指示灯也正常 homekit可以发现设备 就是添加不了 显示无法添加配件  请问连接代码 是11111111 还是98521985呢

**Comment by LouisLee985** [comment]
@jcober 11111111在哪里出现过？

**Comment by LouisLee985** [comment]
TYWE3S FLASH is only 1M Bytes.
It must be 2M Bytes at least.
