### ISSUE TITLE
家庭APP中无法添加

### ISSUE THREAD

**Issue by addcjy1** [LouisLee985/Homekit-Air-Conditioner#6]
您好，[Air_Conditioner_Remote_1.6.0.bin](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/blob/main/firware_bin/Air_Conditioner_Remote_1.6.0.bin)以及[Air_Conditioner_Remote_1.6.0-TYSW-012.bin](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/blob/main/firware_bin/Air_Conditioner_Remote_1.6.0-TYSW-012.bin)分别在ESP-12F以及涂鸦设备上运行，家庭APP中均显示“无法添加配件，发生未知错误”
![image](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/assets/86564859/6c033930-9d33-4ff2-b00a-5fa9f7ba3e0c)

**Comment by LouisLee985** [comment]
FLASH is only 1MB.
PCB打样，焊接。
(https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/issues/5#issuecomment-1616351595)
