### ISSUE TITLE
涂鸦ufo-r1无法使用

### ISSUE THREAD

**Issue by diamondt5353** [LouisLee985/Homekit-Air-Conditioner#7]
![CL_}4MO46BT7ATJM)84G@0D](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/assets/57979092/28099ec7-122c-4f35-b6cc-2c9de6827a70)
[https://go.tuya.com/en/productDetail?code=818dt4kx44e8](url)

**Comment by diamondt5353** [comment]
大佬，这固件可以ota升级吗,配置WiFi后，用192.168.123.124打不开配置界面了

**Comment by LouisLee985** [comment]
Can't ota.
