### ISSUE TITLE
设备无法连接homekit，请帮忙看看错误日志

### ISSUE THREAD

**Issue by jcober** [LouisLee985/Homekit-Air-Conditioner#8]
>>> [ 623044] HomeKit: Got new c
lient: local 192.168.2.112:5556, remote 192.168.2.100:64840
>>> 
[ 623053] HomeKit: [Client 1073693604] Pair Setup Step 1/3

>>> [ 629341] HomeKit: [Client 1
073693604] Pair Setup Step 2/3

>>> [ 629352] HomeKit: Call s_mp_exptmod in integer.c, original 
winsize 6

>>> [ 639046] HomeKit: Call s_mp
_exptmod in integer.c, original winsize 5

>>> [ 644189] HomeKit: [Client 1
073693604] Pair Setup Step 3/3

>>> [ 644218] HomeKit: Call ge_double_scalarmult_vartime_lowmem in ge_low_mem.c

!!! [ 644939] HomeKit: Failed to
 compact HomeKit storage: sector data read error
!!! [ 644946] HomeKit: Failed to write pairing info to HomeKit storage: max number of pairings
!!! [ 644954] HomeKit: [Client 1073693604] Faile
d to store pairing (code -2)

>>> [ 645007] HomeKit: [Client 1
073693604] Disconnected!
>>> [ 645012] HomeKit: [Client 10736936
04] Closing client connection
>>> [ 645018] HomeKit: Free saved_preinit_pairing_context
>>> [ 645023] HomeKit: [Client 0] Clear 
the pairing context

>>> [ 645039] HomeKit: Preiniting pairing context
>>> [ 645043] HomeKit: Using user-specified password: 985-21-985

>>> [ 645063] HomeKit: Call s_mp
_exptmod in integer.c, original winsize 6

>>> [ 651725] HomeKit: Call s_mp
_exptmod in integer.c, original winsize 5

>>> [ 655145] HomeKit: Preinit p
airing context success

>>> [1112863] HomeKit: [Client 1
073691252] Disconnected!
>>> [1112868] HomeKit: [Client 1073691252] Closing client connection

**Comment by LouisLee985** [comment]
https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/issues/5#issuecomment-1616351595

Download gerber,make PCB,soldering.
https://github.com/LouisLee985/Homekit_ESP_AC_IRemote/tree/main/hardware#ac_ir_homekit_usb_type_a
