### ISSUE TITLE
Can I install this over Mixiaoxiao build via web update?

### ISSUE THREAD

**Issue by loyukfai** [LouisLee985/Homekit-Air-Conditioner#9]
I bought a pre-built unit on Taobao which comes with Mixiaoxiao.

However it doesn't work with my AC (Hitachi RAS-E13CAK)

Also, it has some character limit for WPA key

Can I upgrade to this via web to resolve the above issues?

Cheers.

**Comment by LouisLee985** [comment]
1. Connect your device to your FTDI adapter in flash-mode, connecting GPIO-0 to GND or holding down device button while connecting if it uses GPIO-0.
2. Use [flash_download_tool_3.9.5.exe](https://github.com/LouisLee985/Homekit-Air-Conditioner-Remote/blob/main/firware_bin/flash_download_tool_3.9.5_0.zip) to flash this bin in your device:

- Flash the new firmware with SPI DOUT mode 
- @0x0
- DoNotChgBin is unchecked。
- select COM：...，BAUD:115200。
- ERASE...
- START...

**Comment by loyukfai** [comment]
Thanks. So I need to grab a FTDI adapter.

**Comment by loyukfai** [comment]
So I must get a FTDI adapter and not use the web update feature (https://camo.githubusercontent.com/8cfe908d3458805fc5bb42540c6d95d97168246aad537b769fed9ae0460dba39/68747470733a2f2f7261772e6769746875622e636f6d2f4d697869616f7869616f2f455350383236362d49522d484f4d454b49542f6d61737465722f696d6167652f69725f686f6d656b69745f7765625f70616765732e706e67 middle pic), right?

**Comment by LouisLee985** [comment]
Right.

**Comment by loyukfai** [comment]
Thanks. I'll be getting a FTDI adapter and cables to flash it.

https://ibb.co/8jTgGfQ

**Comment by loyukfai** [comment]
Hi, I successfully flashed. Do you have any idea how to add it to Home Assistant?

Thanks!

**Comment by LouisLee985** [comment]
No idea.
The servers like Home Assistant or bridges like HomeBridge are not necessary.
Add it to the Apple home app directly.
